### ISSUE TITLE
Questions about the Nimbus format and custom arguments

### ISSUE THREAD

**Issue by LucyI** [marph91/jimmy#17]
I'm running the windows cli thru the cmd prompt. Attempting to convert notes exported from Nimbus (Fusebase) to markdown. I had thought that the program would allow me to convert files, store them locally, and then import them in a later step, but the only process seems to import immediately to Joplin.

I'm also trying to customize, but neither of these custom arguments have worked:
`jimmy-cli-windows: error: unrecognized arguments: --frontmatter joplin`
`jimmy-cli-windows: error: unrecognized arguments: --output-folder nimbus_note`

Should I be able to output to a folder, for instance to use if I want to import into a different note app besides Joplin? I was hoping to import into Obsidian too...

Also, should the frontmatter argument work? What would be the structure of the command if I wanted to save the conversion to another folder and/or include frontmatter?

**OS**
Win 11

**Comment by marph91** [comment]
The arguments look technically correct. Could you check that you are using the [latest release](https://github.com/marph91/jimmy/releases/tag/v0.0.27)?

With this release it's possible to convert the notes to a folder and then import to Joplin or Obsidian. Frontmatter should work, too. The final command could look like: `jimmy-cli-windows nimbus_note/Example/ --format nimbus_note --output-folder nimbus_note --frontmatter joplin`.

Side note: There is only a simple test file for NimbusNote, so the conversion might need some tweaking. If there are any problems, you can write here.

**Comment by LucyI** [comment]
Thank you I'll try again using the download you just linked, as I'm not sure which versions I have already. (I had downloaded two versions already; one didn't work at all. I looked in properties for each of those .exe files but there is nothing in the details listed for version number. Is there another way on a Windows 11 machine to view the version #?)

Question about your example command: You show the first directory in the path as "nimbus_note", which is identical to the format command, so I'm wondering if that is just coincidence or if it's a requirement that my exported Nimbus files be located in a folder called "nimbus_note"?

**Comment by marph91** [comment]
The version is printed in the log, like `INFO     Jimmy 0.0.28 (Pandoc 3.4)` (but only in newer versions, though). In general it's best to use the latest release as it contains fixes and more test data.

The output folder name can be (almost) arbitrary. The name `nimbus_note` was just taken from your previous example.

**Comment by LucyI** [comment]
This was the result with the most recent version:

```
C:\Users\lucy>jimmy-cli-windows NimbusExportZipped --format nimbus_note --output-folder nimbus_note  --frontmatter joplin
Traceback (most recent call last):
  File "jimmy_cli.py", line 130, in <module>
  File "jimmy_cli.py", line 126, in main
  File "jimmy.py", line 109, in jimmy
  File "pypandoc\__init__.py", line 641, in get_pandoc_version
  File "pypandoc\__init__.py", line 797, in _ensure_pandoc_path
OSError: No pandoc was found: either install pandoc and add it
to your PATH or or call pypandoc.download_pandoc(...) or
install pypandoc wheels with included pandoc.
[PYI-23644:ERROR] Failed to execute script 'jimmy_cli' due to unhandled exception!
```

**Comment by marph91** [comment]
Hmm, might be an issue with Windows 11. It works in my VM and [in the CI](https://github.com/marph91/jimmy/actions/runs/11408808693/job/31747774100), but both use Windows 10. I will try to setup a Windows 11 VM, but it might take some time.

**Comment by LucyI** [comment]
I think this is going to work, thank you. I have to do one notebook at a time, is that expected? And I had to clean up the filenames which were crazy. Also it says it hit some tables that were too complicated to convert to markdown which is fine, and luckily that did not stop the conversion. 

So far I have tested only with the Joplin frontmatter, but I'll also try the Obsidian frontmatter, and also "All" if that is still included in this build?

Thank you so much for this incredibly helpful program. What a nightmare it's been going from Evernote's deterioration to the sinking of Nimbus to the Wild Wild West of notetaking, apparently.

**Comment by marph91** [comment]
> I have to do one notebook at a time, is that expected?

You can put multiple zip files in the same folder. They should be exported in one go. I do the same in a [test case](https://github.com/marph91/jimmy-test-data/tree/master/test_data/nimbus_note/test_2/Demo%20Workspace).

There is also an [option to do a complete server backup](https://nimbusweb.me/guides/settings/account-management-how-to-backup-and-export-your-data/#b3265663460_249) in Nimbus Note, but it requires a premium plan. So I couldn't implement it. If you can provide such a backup, I can try to implement the conversion.

> I had to clean up the filenames which were crazy.

Do you mean the Markdown files are named ok, but the attachments are named crazy, like [here](https://github.com/marph91/jimmy-test-data/tree/e25dbd447fb611d0375f05231154fdfb3344a1aa/reference_data/nimbus_note/test_2)? I think this was done to avoid duplicated filenames (i. e. one file could overwrite another file with same name). Maybe I can implement it in a better readable way.

> it says it hit some tables that were too complicated to convert to markdown

That's fixable in some cases, but I would need an example export to check.

> So far I have tested only with the Joplin frontmatter, but I'll also try the Obsidian frontmatter, and also "All" if that is still included in this build?

Yes, it's still included. I didn't test, but "All" should be compatible with both apps (Obsidian and Joplin).

> Thank you so much for this incredibly helpful program. What a nightmare it's been going from Evernote's deterioration to the sinking of Nimbus to the Wild Wild West of notetaking, apparently.

I'm glad that it's helpful. I was in the same situation once. That's why I built this tool :)

**Comment by LucyI** [comment]
Oh yes sorry, in referring to the filenames I meant the names of each note's folder as exported by Nimbus. I suppose it's kinda my fault; I had 100s of PDFs saved as notes, which when originally uploaded had the PDF titles automatically used as the note title (don't remember if this was Evernote's behavior, or Nimbus', or both). But anyway they had every character under the sun (including en and em spaces) and some were astronomically long filenames, and when I tried to run them through Jimmy it errored. So rather than figure out which filenames I should clean I just cleaned them all.  I could do it in a batch so was not really time-consuming. 

My Nimbus export is each notebook, unzipped, containing all its notes zipped. 

- Notebook 1\

Are you saying I can zip all the notebooks together, and Jimmy will unzip the notebooks and then unzip the notes?

**Comment by marph91** [comment]
> they had every character under the sun (including en and em spaces) and some were astronomically long filenames, and when I tried to run them through Jimmy it errored

If the error occurs again, feel free to share the error and the filename. There is a mechanism to create "safe" filenames that should work in theory. But in practice, there are thousands of edge cases :D

> My Nimbus export is each notebook, unzipped, containing all its notes zipped.
> Are you saying I can zip all the notebooks together, and Jimmy will unzip the notebooks and then unzip the notes?

Oh, probably I need to understand the exported format better. What I can do with the free plan, is to export only single notes to a `note.zip` file. I meant that you can import multiple notes at a time, but you are doing this already.

Does your export look like:

```
root_folder/
  notebook1.zip
  notebook2.zip
  ...
```

And each `notebook.zip` contains multiple `note.zip`?

If you have an export file (as it comes out of the Nimbus export and doesn't contain private data), feel free to share it (here or at my [mail](mailto:martin.d@andix.de)). I could understand the format better and implement the conversion directly.

**Comment by marph91** [comment]
Hi @LucyI, sorry for pinging. Is this issue still relevant for you or did you find a workaround?

**Comment by marph91** [comment]
Closing due to lack of response.
